image: humancellatlas/dss-build-box
# The Docker image `humancellatlas/dss-build-box` is created through a manual process from
# `${DSS_HOME}/Dockerfile.allspark`. See the contents of `${DSS_HOME}/Dockerfile.allspark`
# creation and usage instructions.

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DSS_ES_TIMEOUT: 30
  DSS_UNITTEST_OPTS: "-v"
  TERRAFORM_APPLY_ARGS: "-auto-approve"
  GITHUB_API: "https://api.github.com"

stages:
  - test

before_script:
  - git clone https://$GITHUB_TOKEN@github.com/HumanCellAtlas/data-store.git ~/data-store && cd ~/data-store
  - git checkout $CI_COMMIT_REF_NAME

tag_test:
  stage: test
  script:
    - git remote -v
    - git branch
    - git checkout $CI_COMMIT_REF_NAME
    - git branch
    - git tag "test-tag"
    - git push --force origin $CI_COMMIT_REF_NAME
    - git push --tags
  only:
    - bhannafi-deploy-debug
