image: humancellatlas/dss-build-box

cache:
  paths:
  - chalice/.chalice/venv
  - daemons/dss-sync/.chalice/venv
  - daemons/dss-index/.chalice/venv

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DSS_ES_TIMEOUT: 30
  DSS_UNITTEST_OPTS: "-v"
  TERRAFORM_APPLY_ARGS: "-auto-approve"
  GITHUB_API: "https://api.github.com"

stages:
  - test
  - integration_test
  - deploy_dev
  - release_integration

before_script:
  - if not [[ CI_COMMIT_SHA == $(http GET ${GITHUB_API}/repos/HumanCellAtlas/data-store/commits sha==$CI_COMMIT_REF_NAME | jq -r '.[0]["sha"]') ]]; then exit 1; fi
# TODO: figure out how to get the gitlab-runner to not clone the repo as root - Brian H
  - cp -r /HumanCellAtlas/data-store ~/data-store && cd ~/data-store
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements-dev.txt
  - source environment
  - if [[ -f "environment.$CI_COMMIT_REF_NAME" ]]; then source "environment.$CI_COMMIT_REF_NAME"; fi

unit_tests:
  stage: test
  script:
    - whoami
    - ls -alh /
    - make -j4 parallel_test

test_search:
  stage: test
  script:
    - make -j1 tests/test_search.py

test_aws_indexer:
  stage: test
  variables:
    DSS_UNITTEST_OPTS: "-v TestAWSIndexer"
  script:
    - make -j1 tests/test_indexer.py

test_gcp_indexer:
  stage: test
  variables:
    DSS_UNITTEST_OPTS: "-v TestGCPIndexer"
  script:
    - make -j1 tests/test_indexer.py

test_subscriptions:
  stage: test
  script:
    - make -j1 tests/test_subscriptions.py

integration_test:
  stage: integration_test
  script:
    - make -j1 integration_test

deploy_dev:
  stage: deploy_dev
  script:
    - aws secretsmanager get-secret-value --secret-id ${DSS_SECRETS_STORE}/${DSS_DEPLOYMENT_STAGE}/gcp-credentials.json | jq -r .SecretString > gcp-credentials.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json
    - make deploy-infra
    - make deploy
  only:
    - master

release_integration:
  stage: release_integration
  script:
    - while [[ "pending" == $(scripts/status.sh HumanCellAtlas dcp integration) ]]; do
    -   echo "waiting for DCP Integration test to complete";
    -   sleep 60;
    - done
    - if [[ "success" != $(scripts/status.sh HumanCellAtlas dcp integration) ]]; then
    -   echo "DCP Integration test did not succeed";
    -   exit 1
    - fi
    - scripts/release.sh master integration
  only:
    - master
