language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.6

install:
  - pip install coverage flake8
  - pip install -r requirements.txt

script:
  - ./test/test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
