language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.6
install:
  - pip install coverage flake8
  - pip install -r requirements.txt
script:
  - flake8
  - ./test/test.py
  - ./test/s3blobstoretest.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: JQGeg822bv8s25jWV4fUgWHfR+PfInA/mhdYTWOuPQNqcyPwzDAEkcGecCypXSw1DDtWwuRvYjOx4q4bAx7pDaoWC9vdvM7pJ6LA98r5c+chKb4fom+Eav9VlETl7pzWYz1lCvZ3Gs0mhzEYopivayqD50iAB1eQUJD5uMz4UAr13fu5Gi/Irla7lbuGhdF/7vS9Hh5WyBwOeRgOUtk8cK83AdQol7HvBYPL43KDzzPosACdG2ISQ+wlnyq4nUtI86sBuEWlljv0WRfE3W1sSpXldmQawG9rb42JE96IeDQ5a78QGVcIYPNzD38gZ+95alcBWIjaSIFu5zeCY+h+EavWvHiLzhZip6MqZgX6ZYRAPOOa3FmhF3Kwk1yLOw2EG2VdK9jpV8rUZ9qnhJbQMrrGa/Ci6/OY46ILJNFeRZyNXOUiLxbBYL2rRKFiE/kGTsOTReVy6ZjC4ZWfrqzr8rYmk3L7ou9ln1cUhDeTj3dey7UrcdcqO3MbFYdve4b6G4xdYpei42xpmT7jbYBsdnjxXxLRu6WmoHbNEJ9sfsvi59RFrcBHof+qHyqVlHoNovpr/5RHPFlLL27ORIj8HuG8pTIXUjacKcRhI4/BDJK+dfQ2oODuBi5nbq4n8ccUe2BQpmr6KAcFdR/VuKRAKW5Vgk9c9pqv8+iuHyGv/H4=
    - secure: qwvt/XU+mg1S3l9MMBQ3HvCnsbjvbN67OpOUVqD0QVFQhIn+Ih9LfLBDNC1vxTzHIFtDTQlFcBUL949sHPZjH1QO07B3CNkPLYin2CvmW+4JnDoNNVTsOAXKDJngx6M55FhW1EilfO/Pahm7A0378MP+3vzA6hvzUs0C3R4zgNDLWM/ZIN7CcnbKnI7Q93CyygHee+tMwV4O5v+DjvTVwUHNKX7gqxm3G55m/8dawmp3wB+BEec0v/wD+OOhpTNGNE8GdjXdVUFV7oq3SU4iFQ22Wop32FZmuNgsTA9jNO9WxgiGZEbhk1p0xJjTk0/6zmNW5+acosgiug+ub11Y7I+Jl/hT5XwoYylTfpPXRxqtEwvQdg1AvtMOBS4+VJoMcoWZRpLZz6vZ3QDFnqGYPnjbBxbG2E2UDdcPNEBWUrVD5gqURdzwfSNRmIJpFPXu+Hl4dTtZY4BGZwyhioHO0zg42K86Y76n2qY/6If3TcJhPUiR7DERnBaZ81vgnOvzKjlOqQBS2kfTT8sIPPTPuYKbXymqKxS4ztj+mkFlsGcIIc8uUXtw3XZUKjq4TfxYagrCvP2kJ9m47a0qXsURJGGX/JgapQJp8VzuTvv94qiEjH+OUqTu20NW7/yYtsrv3VocvApOda9A7/uRXtdQw3R21x+kyM4tJyUCtGa2vW8=
