language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.6
install:
  - pip install coverage flake8
  - pip install -r requirements.txt
script:
  - flake8
  - ./test/test.py
  - ./test/s3blobstoretest.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: J+29eVW4dVDg7aNa6L59LPfbE3TfGoRy0lsabpUjdFA8ZCJbxFUoDinrO2TuLVkhabX2WO0Z8ocBrGOpRYpAxBrBRxwYvHXKBdIt0cfiVYLZPAX6kFIRxnfx/J8etxxU/Qh90siyES6oA//4dnwDfwzo/kHfLBSBJExzX7uy1LtcbmhDxkFm1KwUW0ndNsANq9rWB/tAaA12iaWtvxhiEEFWkUVPuFfK9amBMNzMKK8+/hd6AVS5qd2wFO0gbT/zExouQ0PIiqwQDgY3lSMi7/ddW5QysuUrAf+QIyeRI68wc9B3HQh5oAkRzK4/f4ElyotlknZ0WkqF5/NPiJCeW3TzaxogPRDFRBE9o752b5G2JiB2of4JuXpizjg0PO2lthNsqFuvdza7s7orwHnE+j9XoCMq0PKyZQv+cRyTiBBmEasZ1BMB+oPjwXRykTxElwml3yV9NrmL7WyIqJ1hUtFw45cmMR1oBb5hN4GZRJNwa1k1xZlPRqHbJzPR1/U6GJ+0U3R4XSCDFKKTcBNwsmwWIWo/Za+zGgXDi7Nb+9s8WgldQe8TmQyRb7fdrVB9U8oBQouoYc2+xyzBtanMqWrcq5zrMY0AcO0BBQ4yAgdq1BxCSoB4yDOmQrADMxrybchC9p9PnO2S3ucWHzrB+42pqDD4cLgWyeATUZmzfXk=
    - secure: YLDF6DdPz/PqPYlb2rjIciKiecnwKAu6lKJFNatAi/WJ0TyL5sk8Z5exKBecerKlQvKI1aWceyq91sm7WdENkoV9hrRGiYZwT9SIdIj0EVAVixd2b04H+6tNn0RmMae1sBSGW3F5q5nnqoPkqno7f8cAHKOyCY/gcvunxInUckz7umTh/21becB33f1lTGz0oHV8BSQW4D6Qcb/To3VSKpTlYNJPXKnb8PzLd7dYx1NnyPAWn4ibWF3ZGNKLfX8gGxdPyLgZ1tCgJVwAJMpnXVLZTATpqUkhYVN5VhxcY8u01ApkMTGbkOFQ0k4gFUGg0Pkp+k1+fwudRZz9K2D/U0z4EN8GpTzJ2rCJEBPD2BAfTVTQNNnuwAvGdh97DQXJPlOK46S0Hc9mjxgN8eKAb7spJjfKKngtXwryVCdcKQp+U1lxduj1Um+9JiZEiKiIyjiNEbF9J5wVaFbEuMXKSeCyW1yhfEz+8Jm8mLH6YW2T0pYyPnL+Yy1esmIFGrYO+oAJeBvfdOufKjTOEwYNAFjQJTGELrdz0kf3KrV52MjcZyHbYbi77kP354WXmz7rl+LzWDDYSRCBH09/fKOr91WrEwWs3siyj5ZyM87DR+kOYFcillbX0BtXNC3hq2/L8GFC6mAzyipjXqsQi9LzPa26lK8SAvjJcycncR07+ws=
