language: python
cache: pip
python:
- 2.7
- 3.4
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_ead445d7a1e2_key -iv $encrypted_ead445d7a1e2_iv -in gcs-credentials.json.enc -out gcs-credentials.json -d
install:
- pip install coverage flake8
- pip install -r requirements.txt
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
    python: 3.6
env:
  global:
  - DSS_S3_TEST_BUCKET=czi-hca-test
  - DSS_GCS_TEST_BUCKET=czi-hca-test
  - GOOGLE_APPLICATION_CREDENTIALS=gcs-credentials.json
  - secure: 1JF8I9GS1FqMAxaUbqU2TMX+bh6QZ08GZcZaRZf+ejZtkNNtvzkobcfej9jGZDnKc3fOhZ3ShEaTx2RW5stua21C6XGYF01WzPxkSJi1JkJrDwCdk4hAOExLbiLY4uHnLTIreIsS4Ig9SQhGpxDl2V0GtHhozSk2QwUX2zuCDuSe7etgsSl01Q0vq2JIG+az+X3NZQZgRHUAwyOxlw8+4lLcVpqSgkbTSA2rIvQTN1SZfB3iIs3BCMzZmWOQ6S1q6RA/5HajZJQfUq/03arzScYga6Phb5jQnNwq0W9RuFLMlk2Zz7rx3tRzb1THVGKG+NuGf1ixYBu3VFbe4hfwZij3QceZYMf3xSJf8o5tXh4U3mgJjCVRaeSHXcB19qwPDCZAf0DxdM+L/oFIjdhw+DNSwP20kR2pkTL6LByBVuh3zSG7tzHIAvNZbyMM75PRk8WocMfVwxh1/fFR2mbR9n4Q6H0fkgJq0vvG+k//X2cbvOKy342Dl2KvndsDEhslmYD3cChTBWqqxSNWW2kpjwVhL4YA5juxt4Gr8GI8vGEKrLRigpSrPbA+lob+nRSBy0EmtjLwRfbPOMBTaihnC9OX4gdZzd33cbwL3LdgjBXMgehvkh4lc4O6KiSbjHSNz9LlyEwZxi8QxCxF4aXxf9HSAmkaimdrPPsu3azEWXY=
  - secure: aUeZ6AYYwEvHmHd9ztzfCTphP4xJk9RkwocB8VOdVKnN2L7mh52aMoC7YNMTGPPbcfkYFUu7hDJb8NET64M7POG5ocujNA2jz8Ky4ZDoZS7RQXofqG4eysr5ODxwlalBAvbEFIXbyS5b5phIbSzuScOfigGIK7h8s+qW1bR9w2rGOl1At3iPO95BjOtHL53on7lflhHGRzsh2GqtFQehz7QhG7Rzb3udYLQDApMnFJ8CbPb45fJnXhSsQW92Zx16kDUPObi09CAX13GrN1BZ0d8iMY7iMa1DDp6R+maXLh9C4TNIe2afpxibw+tmEu0Znwiv++yQ8E8YaZXUUjvtuYUceXEQkZiUwYnzv7s/QVj5bjjQSgMd8RlOjp0baAvG+L5e+4J1/KxHg+eV5FA7ys7xHurosLVa54ev4vzZBQCI0XbWHsr6h8z7jjUV4dWFW4aQ89GxZ2T8at/OrAVDU82+rhtOSgHNstcMrDS5Tyz+DHPjg6osuhpqcrvyLOvYze2XM2G4N4V3apHtVmjbjsooST5aSsVgCW0Xc6KQZyeBFTydtiEYJ5huP2Q7peTAD9HVAISRjlatFloMn7u3vk5pyf35YIdMRugnQnSQpGX29AobidyCuM9IDJ0gtBNk//FTWLfvk+Jvo0iOslnaJ+g3hspb049UWQvTf0xUiC8=
