#
# How to use docker-compose:
#
#   docker-compose build         - creates an hca_dss docker image
#
#   docker-compose up dss        - starts hca_dss container, running dss-api, attached to terminal
#
# then in another terminal tab, you can interact with the API
#
#   curl http://localhost:5000/v1/files
#
# or
#   docker-compose run dss bash  - starts hca_dss container, running bash
#
# When you are done, cleanup with:
#
#   docker-compose down
#
# Notes:
#
#   - Your ~/.aws folder is mounted in the container in case you wish to use your AWS credentials.
#
#   - This folder (.) is mounted over the packaged code, so changes you make can be picked up without re-building.
#
version: '3'
services:
  dss:
    build: .
    volumes:
      - ~/.aws:/root/.aws
      - .:/code/data-store
    ports:
      - 5000:5000
